-- 0049 — remember which language each advice row was written in.
--
-- Advice prose is generated by the LLM in ONE language and stored as text. Until now nothing
-- recorded which one, and the auto-trigger (geo pipeline → /api/internal/advice/run) never passed a
-- language at all, so every automatically generated advice was Azerbaijani. A Russian farmer opened
-- the field page and read the analysis in Azerbaijani.
--
-- With the language on the row, the read endpoint can tell the reader "this was written in another
-- language" and offer to regenerate, and the auto-trigger can generate in the owner's language.
-- Existing rows really are Azerbaijani, so the default backfills them correctly.
alter table public.advice add column if not exists lang text not null default 'az';

-- Newest-advice-per-language lookup (the read path asks for "newest row for this field").
create index if not exists advice_field_lang_idx on public.advice (field_id, lang, generated_at desc);
