"""Pydantic request/response models."""
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, EmailStr, Field


class OrgRole(str, Enum):
    owner = "owner"
    admin = "admin"
    agronomist = "agronomist"
    worker = "worker"
    viewer = "viewer"


class UserRole(str, Enum):
    """Global marketplace persona (0031), distinct from OrgRole membership."""
    farmer = "farmer"
    lab = "lab"
    consultant = "consultant"
    supplier = "supplier"


# ---- auth ----
class SignupIn(BaseModel):
    """Signup is EMAIL ONLY. Everything below the address is optional and stays here purely so the
    older callers (the registration wizard, any bookmarked client) keep working unchanged — nothing
    is required of a new farmer but a working mailbox.

    `password` is Optional[str] = None, NOT Field(None, min_length=8): the length is checked in the
    router instead, which raises the already-mapped `password_too_short` as a clean 400 rather than
    a 422 constraint array. `locale` deliberately survives the simplification — it decides the
    language of every later email (weekly digest, welcome) and of the AI advice generated by cron,
    none of which has a request to read a header from. `role` defaults to farmer; a provider signs
    up through the same route and sends its own value.
    """
    email: EmailStr
    password: Optional[str] = None
    full_name: Optional[str] = None
    locale: str = "az"
    role: UserRole = UserRole.farmer
    country: Optional[str] = None
    region: Optional[str] = None
    name_public: bool = True  # farmer name visibility (New-B); default visible
    onboarding: Optional[dict] = None  # E13 landing quiz answers, carried in from localStorage


class LoginIn(BaseModel):
    email: EmailStr
    password: str


class MagicLinkIn(BaseModel):
    """Request a sign-in link. Both signup and login — the caller does not say which, and the
    response never reveals which it was."""
    email: EmailStr
    locale: Optional[str] = None


class MagicLoginIn(BaseModel):
    """Redeem a sign-in link. POST-only body, never a query parameter: a token in a URL that the
    browser navigates to ends up in history, in the Referer of every asset the page loads, and in
    access logs. The bounds are a cheap sanity filter — the real check is the sha256 lookup."""
    token: str = Field(min_length=16, max_length=512)


class VerifyOtpIn(BaseModel):
    email: EmailStr
    code: str


class ResendOtpIn(BaseModel):
    email: EmailStr


class UserOut(BaseModel):
    id: str
    email: EmailStr
    full_name: Optional[str] = None
    locale: str = "az"
    is_admin: bool = False
    role: UserRole = UserRole.farmer
    country: Optional[str] = None
    region: Optional[str] = None


# ---- organizations / membership ----
class OrgIn(BaseModel):
    name: str
    country: str = "AZ"


class OrgOut(BaseModel):
    id: str
    name: str
    country: str
    role: Optional[OrgRole] = None


class InviteIn(BaseModel):
    email: EmailStr
    role: OrgRole = OrgRole.viewer


class RoleChangeIn(BaseModel):
    role: OrgRole


# ---- farms ----
class FarmIn(BaseModel):
    org_id: str
    name: str
    region: Optional[str] = None


class FarmOut(BaseModel):
    id: str
    org_id: str
    name: str
    region: Optional[str] = None


# ---- fields ----
class FieldIn(BaseModel):
    farm_id: str
    # OPTIONAL, and this line is what makes the auto-naming in routers/fields.py reachable at all.
    # That router already generates "Sahə 1", "Sahə 2", … under an advisory lock when the farmer
    # leaves the box empty — but while this was `name: str` Pydantic rejected the request with 422
    # before the handler ran, so the whole feature was dead behind a validator. A missing name and
    # an empty string both mean "you name it"; the handler normalises with `(body.name or "").strip()`.
    name: Optional[str] = None
    # GeoJSON polygon coordinates: [[[lon,lat], ...]] (single ring, first ring used)
    geometry: dict[str, Any]


class FieldOut(BaseModel):
    id: str
    farm_id: str
    org_id: str
    name: str
    area_ha: Optional[float] = None
    mgrs_tiles: Optional[list[str]] = None


class FieldMetadataIn(BaseModel):
    crop_type: str
    crop_cycle: Optional[str] = None
    region: Optional[str] = None
    economic_region: Optional[str] = None
    variety: Optional[str] = None
    planting_date: Optional[str] = None
    expected_harvest: Optional[str] = None
    difficulties: list[Any] = []
    soil_type: Optional[str] = None
    soil_ph: Optional[float] = None
    irrigation_method: Optional[str] = None
    irrigation_available: bool = False
    previous_crop: Optional[str] = None
    rotation_history: list[Any] = []
    fertilizer_history: list[Any] = []
    seeding_density: Optional[float] = None
    growth_stage: Optional[str] = None
    elevation_m: Optional[float] = None
    slope_deg: Optional[float] = None
    aspect_deg: Optional[float] = None
    tillage_practice: Optional[str] = None
    target_yield: Optional[float] = None
    prior_yields: list[Any] = []
    pest_history: list[Any] = []
    notes: Optional[str] = None


# ---- subsidy (§30) ----
class SubsidyCalcIn(BaseModel):
    year: int = 2026
    subsidy_type: str
    crop_group: str
    crop: str
    intensity: Optional[str] = None
    region_category: Optional[str] = None
    region_rayon: Optional[str] = None
    irrigation: Optional[str] = None
    planting_period: Optional[str] = None
    quantity_ha: Optional[float] = None
    tons: Optional[float] = None
    modifiers: dict[str, Any] = {}
    field_id: Optional[str] = None
    as_of_date: Optional[str] = None   # ISO date; drives the apple/peach cutoff


class SubsidySaveIn(SubsidyCalcIn):
    org_id: Optional[str] = None


# ---- scouting / tasks / operations / yields (§14–16) ----
class ScoutingIn(BaseModel):
    field_id: str
    category: str                       # pest|disease|weed|nutrient|water|damage|other
    # 1..5, matching the <input type="number" min=1 max=5> the UI has always rendered. This was
    # Optional[str] against a client sending Number(severity): Pydantic 2.10 does not coerce int →
    # str in lax mode, so EVERY note carrying a severity was rejected with a 422 — and the offline
    # outbox replayed the same rejected body forever. The COLUMN stays text (see routers/scouting).
    severity: Optional[int] = Field(None, ge=1, le=5)
    note: Optional[str] = None
    lon: Optional[float] = None
    lat: Optional[float] = None
    photos: list[str] = []              # storage paths (from /api/uploads)
    color: Optional[str] = None         # pin colour name; validated against PIN_COLORS in the router


class ScoutingUpdateIn(BaseModel):
    """Partial edit of one observation (6.5).

    Every field is optional AND nullable, and the router reads `model_fields_set` rather than the
    values: that is the only way "absent" and "explicitly set to null" stay distinguishable, so a
    farmer can clear a note's coordinates without also clearing its text.
    """
    category: Optional[str] = None
    severity: Optional[int] = Field(None, ge=1, le=5)
    note: Optional[str] = None
    lon: Optional[float] = None
    lat: Optional[float] = None
    color: Optional[str] = None
    status: Optional[str] = None        # open|resolved — resolved_at is stamped by the router


class TaskIn(BaseModel):
    org_id: str
    title: str
    type: Optional[str] = None
    farm_id: Optional[str] = None
    field_id: Optional[str] = None
    assigned_to: Optional[str] = None
    due_date: Optional[str] = None
    priority: Optional[str] = None
    notes: Optional[str] = None


class TaskStatusIn(BaseModel):
    status: str                         # todo|in_progress|done|cancelled


class OperationIn(BaseModel):
    field_id: str
    type: str                           # planting|spraying|fertilizing|irrigation|harvest|tillage|other
    performed_on: str
    inputs: list[Any] = []              # [{product,rate,unit}]
    cost: Optional[float] = None
    currency: str = "AZN"
    phi_days: Optional[int] = None      # pre-harvest interval (days) — spray safety countdown (B6)
    notes: Optional[str] = None


class YieldIn(BaseModel):
    field_id: str
    season_year: int
    crop_type: Optional[str] = None
    yield_value: Optional[float] = None
    yield_unit: Optional[str] = None    # t_ha|kg|t
    area_ha: Optional[float] = None
    revenue: Optional[float] = None     # total revenue (AZN) — for per-field P&L (0032)
    price: Optional[float] = None       # optional price per unit (AZN)
    notes: Optional[str] = None


# ---- marketplace: provider profiles + catalog (0031) ----
class ProviderIn(BaseModel):
    kind: UserRole                       # lab | consultant | supplier
    company: str = Field(min_length=1)
    bio: Optional[str] = None
    specializations: list[str] = []
    country: Optional[str] = None
    region: Optional[str] = None
    address: Optional[str] = None
    coverage: Optional[str] = None
    phone: Optional[str] = None


class ProviderOut(BaseModel):
    id: str
    user_id: str
    kind: str
    company: str
    bio: Optional[str] = None
    specializations: list[str] = []
    country: Optional[str] = None
    region: Optional[str] = None
    address: Optional[str] = None
    coverage: Optional[str] = None
    phone: Optional[str] = None
    rating: Optional[float] = None
    order_count: int = 0
    featured: bool = False


class CatalogItemIn(BaseModel):
    name: str = Field(min_length=1)
    category: Optional[str] = None
    unit: Optional[str] = None
    price: Optional[float] = None
    currency: str = "AZN"
    description: Optional[str] = None


class CatalogItemOut(CatalogItemIn):
    id: str
    provider_id: str


# ---- marketplace: messaging (0031) ----
class StartConversationIn(BaseModel):
    other_user_id: str
    kind: str = "peer"                   # peer | provider
    body: Optional[str] = None           # optional first message


class MessageIn(BaseModel):
    body: str = Field(min_length=1)


class MessageOut(BaseModel):
    id: str
    sender_id: str
    body: str
    created_at: str
    mine: bool = False


class ConversationOut(BaseModel):
    id: str
    other_user_id: str
    other_name: Optional[str] = None
    other_role: Optional[str] = None
    # Provider identity is the company, not the person — the Messages list shows "AgroLab MMC",
    # not the individual who registered it. Null for farmer↔farmer threads.
    other_company: Optional[str] = None
    # The counterpart closed their account (users.deleted_at). Deletion is anonymisation, not a
    # row delete (0052), so the thread survives and stays readable — but the client must not
    # invite the farmer to keep writing into it.
    other_deleted: bool = False
    kind: str = "peer"
    last_text: Optional[str] = None
    last_at: Optional[str] = None
    unread: int = 0


# ---- messages: people directory (task 3) ----
class DirectoryPersonOut(BaseModel):
    """One row of the "who can I write to" directory.

    Providers and farmers share this shape so the client renders one card component; the fields
    that do not apply are simply null (a farmer has no company/rating, a provider has no crop)."""
    user_id: str
    name: str                            # primary label: company for providers, display name for farmers
    role: str                            # farmer | lab | consultant | supplier
    company: Optional[str] = None
    bio: Optional[str] = None
    specializations: list[str] = []
    country: Optional[str] = None
    region: Optional[str] = None
    crop: Optional[str] = None           # farmers only — the crop that put them in this list
    rating: Optional[float] = None
    featured: bool = False
    provider_id: Optional[str] = None    # provider_profiles.id, for /catalog deep links
    match: Optional[str] = None          # why this person is here: provider | crop | region
    conversation_id: Optional[str] = None  # existing thread, if any — open it instead of starting one


class DirectoryScopeOut(BaseModel):
    """What the farmer list was scoped BY. Empty lists mean "we had nothing to match on" — the
    client should say so (add a field / set your region) rather than imply nobody is out there."""
    crops: list[str] = []
    regions: list[str] = []


class DirectoryOut(BaseModel):
    providers: list[DirectoryPersonOut] = []
    farmers: list[DirectoryPersonOut] = []
    scope: DirectoryScopeOut = DirectoryScopeOut()


# ---- messages: the Agradex AI pseudo-conversation (task 2) ----
# NOTE: the assistant is NOT a public.users row and has no public.conversations row. It is a
# synthetic participant the API describes and the client pins at the top of the Messages list.
# Its transcript lives in public.ai_chat_messages, keyed by FIELD — which is why every shape
# below carries a field id instead of a conversation id.
class AssistantFieldOut(BaseModel):
    field_id: str
    org_id: str
    name: str
    crop: Optional[str] = None
    area_ha: Optional[float] = None
    message_count: int = 0
    last_text: Optional[str] = None
    last_at: Optional[str] = None
    # Quota is per ORGANIZATION, not per field: two fields in the same org share one allowance.
    chat_limit: int = 0
    chat_used: int = 0
    chat_enabled: bool = False


class AssistantInfoOut(BaseModel):
    id: str                              # sentinel id, never a uuid — see routers/chat.py ASSISTANT_ID
    name: str
    role: str = "assistant"
    configured: bool = False             # LLM key present; false ⇒ the thread is read-only
    default_field_id: Optional[str] = None
    last_text: Optional[str] = None      # newest turn across all the caller's fields (list preview)
    last_at: Optional[str] = None
    fields: list[AssistantFieldOut] = []


class AssistantMessageIn(BaseModel):
    body: str = Field(min_length=1)
    locale: Optional[str] = None         # overrides X-Locale; see routers/advice.py::_resolve_locale


class AssistantTurnOut(BaseModel):
    """Deliberately a superset of MessageOut so one bubble component renders human and AI threads."""
    id: str
    sender_id: str                       # ASSISTANT_ID for AI turns, the human's uuid otherwise
    sender_name: Optional[str] = None
    body: str
    created_at: str
    mine: bool = False
    role: str = "user"                   # user | assistant


class AssistantThreadOut(BaseModel):
    assistant: AssistantInfoOut
    field: AssistantFieldOut
    messages: list[AssistantTurnOut] = []
    configured: bool = False
    chat_limit: int = 0
    chat_used: int = 0
    chat_enabled: bool = False


class AssistantReplyOut(BaseModel):
    reply: str
    # False ⇒ the reply was a tier/quota refusal: nothing was written to ai_chat_messages and
    # `messages` is empty, so the client must render it as a transient system bubble and NOT
    # expect it back on the next history fetch.
    persisted: bool = True
    messages: list[AssistantTurnOut] = []
    chat_limit: int = 0
    chat_used: int = 0
    chat_enabled: bool = False


# ---- fertilizer plans (E8, 0031) ----
class FertilizerPlanIn(BaseModel):
    product: str = Field(min_length=1)
    category: Optional[str] = None
    zone: Optional[str] = None
    dose: Optional[str] = None
    planned_on: Optional[str] = None     # ISO date
    status: str = "planned"
    source: str = "manual"
    notes: Optional[str] = None


class FertilizerPlanOut(FertilizerPlanIn):
    id: str
    field_id: str


# ---- field photos (E10, 0031) ----
class FieldPhotoOut(BaseModel):
    id: str
    field_id: str
    photo_path: str
    ai_label: Optional[str] = None
    ai_condition: Optional[str] = None
    ai_notes: Optional[str] = None
    created_at: str
